<?php

namespace SRVDV\ServerBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AlertesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlertesRepository extends EntityRepository
{
}
