<?php

namespace Proxies\__CG__\SRVDV\ServerBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Filiere extends \SRVDV\ServerBundle\Entity\Filiere implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'id', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'dateFiliere', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'nom', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'User', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'anneeFiliere', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'niveau');
        }

        return array('__isInitialized__', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'id', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'dateFiliere', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'nom', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'User', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'anneeFiliere', '' . "\0" . 'SRVDV\\ServerBundle\\Entity\\Filiere' . "\0" . 'niveau');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Filiere $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function __toString()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', array());

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFiliere($dateFiliere)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFiliere', array($dateFiliere));

        return parent::setDateFiliere($dateFiliere);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFiliere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFiliere', array());

        return parent::getDateFiliere();
    }

    /**
     * {@inheritDoc}
     */
    public function setNom($nom)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNom', array($nom));

        return parent::setNom($nom);
    }

    /**
     * {@inheritDoc}
     */
    public function getNom()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNom', array());

        return parent::getNom();
    }

    /**
     * {@inheritDoc}
     */
    public function setUser($User)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUser', array($User));

        return parent::setUser($User);
    }

    /**
     * {@inheritDoc}
     */
    public function getUser()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUser', array());

        return parent::getUser();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', array($niveau));

        return parent::setNiveau($niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', array());

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setAnneeFiliere(\SRVDV\ServerBundle\Entity\Annee $anneeFiliere = NULL)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAnneeFiliere', array($anneeFiliere));

        return parent::setAnneeFiliere($anneeFiliere);
    }

    /**
     * {@inheritDoc}
     */
    public function getAnneeFiliere()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAnneeFiliere', array());

        return parent::getAnneeFiliere();
    }

}
